spring:
  application.name: algorithm-trading
  config.import: optional:file:.env[.properties]

coinone.api:
  public-url: https://api.coinone.co.kr/public/v2
  private-url: https://api.coinone.co.kr/v2.1
  access-token: ${coinone-access-token}
  secret-key: ${coinone-secret-key}
  connection-timeout: 3000
  read-timeout: 5000
  signature-algorithm: HmacSHA512

binance.api:
  url: https://api.binance.com
  access-token: ${binance-access-token}
  secret-key: ${binance-secret-key}
  connection-timeout: 3000
  read-timeout: 5000
  signature-algorithm: HmacSHA256


