spring:
  application.name: algorithm-trading
  config.import: optional:file:.env[.properties]

coinone.api:
  public-url: https://api.coinone.co.kr/public/v2
  private-url: https://api.coinone.co.kr/v2.1
  access-token: ${COINONE_ACCESS_TOKEN}
  secret-key: ${COINONE_SECRET_KEY}
  connection-timeout: 3000
  read-timeout: 5000
  signature-algorithm: HmacSHA512

binance.api:
  url: https://api.binance.com
  access-token: ${BINANCE_ACCESS_TOKEN}
  secret-key: ${BINANCE_SECRET_KEY}
  connection-timeout: 3000
  read-timeout: 5000
  signature-algorithm: HmacSHA256


